### ISSUE TITLE
Directly accessing hour data from URLs

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/las9#53]
Hi Devs,

I have a use case where I will access a specific data set based on the current date and time and pass this information to the URL of LAS to access the dataset. While by default it works accessing the date, the time seems to not work and automatically goes to 0000hours of the specified date.

sharing a snippet of the URL with the date and time info below for example if I set 02-Mar-2023, 16:00 hours, it will loads the LAS product page with 02-Mar-2023 00:00 hours instead. May I know if this can be improved?
`
...
%22:%2202-Mar-2023%2016:00%22,%20%22thi%22:%2202-Mar-2023%2016:00%22%
...
`

Also would like to share that, at times it will return with an error when accessing an exact date. I have not been able to figure out when it works and when it doesnt. It is fine when I add a new dataset but just fails probably after an auto update, for only some datasets. I will keep u informed if I figure out.
`
Data set ingested with unknown status. May not display correctly.
`

Thank you very much.

**Comment by noaaroland** [comment]
Does the UI, show a menu for choosing the hour? In general the code is able to figure out when a data set requires a selector on the time axis for choosing the hour. [This data set for example is every six hours](https://data.pmel.noaa.gov/uaf/las/UI.html#%7B%22id%22:0,%20%22targetPanel%22:1,%20%22operation%22:%22Plot_2D_XY%22,%20%22variableHashes%22:%5B%22c7bcb11862dded590c37d3df92c9a510%22%5D,%20%22datasetHashes%22:%5B%22e2fdc32392a205c5a61abc107d04d92c%22%5D,%20%22analysis%22:%5Bnull%5D,%20%22axesSets%22:%5B%7B%22xlo%22:%220%22,%20%22xhi%22:%22360%22,%20%22ylo%22:%22-90%22,%20%22yhi%22:%2290%22,%20%22zlo%22:null,%20%22zhi%22:null,%20%22tlo%22:%2201-Jan-1893%2000:00%22,%20%22thi%22:%2201-Jan-1893%2000:00%22%7D%5D,%20%22dataQualifiers%22:null,%20%22dataConstraints%22:null,%20%22requestProperties%22:%5B%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22land_type%22,%20%22value%22:%22contour%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22interpolate_data%22,%20%22value%22:%220%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22margins%22,%20%22value%22:%221%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22deg_min_sec%22,%20%22value%22:%220%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22set_aspect%22,%20%22value%22:%221%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22data_count%22,%20%22value%22:%221%22%7D%5D%7D).  

If there are no hour selectors in the UI, then LAS may choose to ignore the hour part of the date/time input. If the data source is public or you can supply a sample I can look at it in the debugger to see if I can figure out why LAS is having trouble determining that the time axis needs the hour menu.

**Comment by haze1986** [comment]
Hi Roland, thanks again for looking into this. There is hour selector for the dataset and the example you shared could be used to show what I meant. To replicate:

1. Access the data set and change the tine to 0600, click update
2. Copy the url and paste it on another browser (tested on incognito), the url can be seen to register the new time of 0600
3. When the dataset loads on new browser, it always goes back to 0000hours

Hope this helps, and if it can be implemented to allow setting the time from the url.

**Comment by haze1986** [comment]
Hi Roland, may I know if this can be fixed or is a limitation?

**Comment by noaaroland** [comment]
It's most certainly a bug, but no timeline for when I can fix it.

**Comment by noaaroland** [comment]
This is fixed with [LAS v9.8.1 release](https://github.com/NOAA-PMEL/las9/releases/tag/v9.8.1). [This link should open the data set above with hour 12 selected.](https://data.pmel.noaa.gov/uaf/las/UI.html#%7B%22id%22:0,%20%22targetPanel%22:1,%20%22operation%22:%22Plot_2D_XY%22,%20%22variableHashes%22:%5B%22c7bcb11862dded590c37d3df92c9a510%22%5D,%20%22datasetHashes%22:%5B%22e2fdc32392a205c5a61abc107d04d92c%22%5D,%20%22analysis%22:%5Bnull%5D,%20%22axesSets%22:%5B%7B%22xlo%22:%220%22,%20%22xhi%22:%22360%22,%20%22ylo%22:%22-90%22,%20%22yhi%22:%2290%22,%20%22zlo%22:null,%20%22zhi%22:null,%20%22tlo%22:%2201-Jan-1893%2012:00%22,%20%22thi%22:%2201-Jan-1893%2012:00%22%7D%5D,%20%22dataQualifiers%22:null,%20%22dataConstraints%22:null,%20%22requestProperties%22:%5B%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22land_type%22,%20%22value%22:%22contour%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22interpolate_data%22,%20%22value%22:%220%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22margins%22,%20%22value%22:%221%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22deg_min_sec%22,%20%22value%22:%220%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22set_aspect%22,%20%22value%22:%221%22%7D,%7B%22id%22:0,%20%22type%22:%22ferret%22,%20%22name%22:%22data_count%22,%20%22value%22:%221%22%7D%5D%7D)

I'm closing this. If it still does not work for your particular data set you can reopen the issue and provide details.
