### ISSUE TITLE
Make a product that plots timeseries locations and profile locations for DSG data sets that are a collections of timeseries or profiles at different points.

### ISSUE THREAD

**Issue by noaaroland** [NOAA-PMEL/las9#76]

**Comment by noaaroland** [comment]
Here is an example. This works with the special build Josh prepared for me to test.


![LAS - Google Chrome_292](https://user-images.githubusercontent.com/16550018/112014026-86061480-8af8-11eb-94a7-b4c52567eca9.png)

**Comment by noaaroland** [comment]
And here is an example from a profile data set.
![LAS - Google Chrome_294](https://user-images.githubusercontent.com/16550018/112025679-6a543b80-8b03-11eb-9c5b-a18476bed171.png)

**Comment by shaunwbell** [comment]
> And here is an example from a profile data set.
@noaaroland - probably jumping the gun here given that its just a n image you've uploaded, but it looks like your ALAMO example will average over the Z axis for each profile (and then plot the values at lat/lon).  Will we be able to change the aggregation function? (say... min(z) or max(z) instead of ave(z) ) for coloring the point?
